package main

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

func TestGenerate_CheckedInTaxonomyIsCurrent(t *testing.T) {
	root := filepath.Join("..", "..", "..")
	generated, err := generate(filepath.Join(root, "agentcore", "session", "event.go"))
	if err != nil {
		t.Fatal(err)
	}

	output := filepath.Join(root, "frontend", "src", "features", "chat", "eventKinds.generated.ts")
	want, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(generated, want) {
		t.Fatalf("%s is stale; run go generate ./agentcore/session", output)
	}
}

func TestGenerate_UsesOnlyTypedEventKindConstants(t *testing.T) {
	directory := t.TempDir()
	source := filepath.Join(directory, "event.go")
	if err := os.WriteFile(source, []byte(`package session
type EventKind string
const (
	KindStarted EventKind = "Started"
	unrelated = "Ignored"
	KindEnded EventKind = "Ended"
)
`), 0o600); err != nil {
		t.Fatal(err)
	}

	got, err := generate(source)
	if err != nil {
		t.Fatal(err)
	}
	want := `// Code generated by go generate ./agentcore/session; DO NOT EDIT.

export type EventKind =
  | 'Started'
  | 'Ended'
`
	if string(got) != want {
		t.Fatalf("generated taxonomy:\n%s\nwant:\n%s", got, want)
	}
}
