// Command eventkindgen generates the frontend's durable event taxonomy from
// the published Go contract.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strconv"
	"strings"
)

func main() {
	source := flag.String("source", "", "Go source containing EventKind constants")
	output := flag.String("output", "", "generated TypeScript output")
	flag.Parse()

	if *source == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "eventkindgen: -source and -output are required")
		os.Exit(2)
	}

	generated, err := generate(*source)
	if err != nil {
		fmt.Fprintf(os.Stderr, "eventkindgen: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "eventkindgen: write output: %v\n", err)
		os.Exit(1)
	}
}

func generate(source string) ([]byte, error) {
	file, err := parser.ParseFile(token.NewFileSet(), source, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("parse source: %w", err)
	}

	var kinds []string
	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.CONST {
			continue
		}
		for _, specification := range general.Specs {
			value, ok := specification.(*ast.ValueSpec)
			if !ok || !isEventKind(value.Type) {
				continue
			}
			if len(value.Names) != len(value.Values) {
				return nil, fmt.Errorf("EventKind declaration must assign every constant explicitly")
			}
			for i, expression := range value.Values {
				literal, ok := expression.(*ast.BasicLit)
				if !ok || literal.Kind != token.STRING {
					return nil, fmt.Errorf("%s must be a string literal", value.Names[i].Name)
				}
				kind, err := strconv.Unquote(literal.Value)
				if err != nil {
					return nil, fmt.Errorf("unquote %s: %w", value.Names[i].Name, err)
				}
				kinds = append(kinds, kind)
			}
		}
	}
	if len(kinds) == 0 {
		return nil, fmt.Errorf("no EventKind constants found")
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by go generate ./agentcore/session; DO NOT EDIT.\n\n")
	output.WriteString("export type EventKind =\n")
	for _, kind := range kinds {
		fmt.Fprintf(&output, "  | %s\n", typescriptString(kind))
	}
	return output.Bytes(), nil
}

func typescriptString(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	value = strings.ReplaceAll(value, `'`, `\'`)
	return `'` + value + `'`
}

func isEventKind(expression ast.Expr) bool {
	identifier, ok := expression.(*ast.Ident)
	return ok && identifier.Name == "EventKind"
}
