// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';

export function AcceptPlan(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function ListProjectFiles():Promise<Array<string>>;

export function ListSessions():Promise<Array<session.SessionSummary>>;

export function Model():Promise<string>;

export function ResolveToolPermission(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SendPlanPrompt(arg1:string,arg2:string):Promise<void>;

export function SendPrompt(arg1:string,arg2:string):Promise<void>;

export function SessionHistory(arg1:string):Promise<Array<session.SessionEvent>>;

export function Stop(arg1:string):Promise<void>;
