// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ResolveToolPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveToolPermission'](arg1, arg2, arg3);
}

export function SendPrompt(arg1, arg2) {
  return window['go']['main']['App']['SendPrompt'](arg1, arg2);
}

export function Stop(arg1) {
  return window['go']['main']['App']['Stop'](arg1);
}
