// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptPlan(arg1) {
  return window['go']['main']['App']['AcceptPlan'](arg1);
}

export function ClosePty(arg1) {
  return window['go']['main']['App']['ClosePty'](arg1);
}

export function Commit(arg1) {
  return window['go']['main']['App']['Commit'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GenerateCommitMessage() {
  return window['go']['main']['App']['GenerateCommitMessage']();
}

export function GitStatus() {
  return window['go']['main']['App']['GitStatus']();
}

export function InitRepo() {
  return window['go']['main']['App']['InitRepo']();
}

export function ListCommands() {
  return window['go']['main']['App']['ListCommands']();
}

export function ListProjectFiles() {
  return window['go']['main']['App']['ListProjectFiles']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function Model() {
  return window['go']['main']['App']['Model']();
}

export function ResizePty(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizePty'](arg1, arg2, arg3);
}

export function ResolveToolPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveToolPermission'](arg1, arg2, arg3);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function SendPlanPrompt(arg1, arg2) {
  return window['go']['main']['App']['SendPlanPrompt'](arg1, arg2);
}

export function SendPrompt(arg1, arg2) {
  return window['go']['main']['App']['SendPrompt'](arg1, arg2);
}

export function SessionHistory(arg1) {
  return window['go']['main']['App']['SessionHistory'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['main']['App']['SetWorkspace'](arg1);
}

export function StartPty(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartPty'](arg1, arg2, arg3);
}

export function Stop(arg1) {
  return window['go']['main']['App']['Stop'](arg1);
}

export function Workspace() {
  return window['go']['main']['App']['Workspace']();
}

export function WritePty(arg1, arg2) {
  return window['go']['main']['App']['WritePty'](arg1, arg2);
}
