// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {command} from '../models';
import {session} from '../models';

export function AcceptPlan(arg1:string):Promise<void>;

export function ClosePty(arg1:string):Promise<void>;

export function Commit(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function FileDiff(arg1:string):Promise<string>;

export function GenerateCommitMessage():Promise<string>;

export function GitStatus():Promise<main.GitStatus>;

export function InitRepo():Promise<void>;

export function ListCommands():Promise<Array<command.Command>>;

export function ListProjectFiles():Promise<Array<string>>;

export function ListSessions():Promise<Array<session.SessionSummary>>;

export function Model():Promise<string>;

export function ResizePty(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveToolPermission(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SelectWorkspace():Promise<string>;

export function SendPlanPrompt(arg1:string,arg2:string):Promise<void>;

export function SendPrompt(arg1:string,arg2:string):Promise<void>;

export function SessionHistory(arg1:string):Promise<Array<session.SessionEvent>>;

export function SetWorkspace(arg1:string):Promise<void>;

export function StartPty(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Stop(arg1:string):Promise<void>;

export function Workspace():Promise<string>;

export function WritePty(arg1:string,arg2:string):Promise<void>;
