// Static catalog of MCPs for the marketplace-style view inside settings.
// Presentation only (Visual phase): hardcoded data, no backend connection and
// no real MCP servers. When the integration lands, this list will be replaced
// by the backend's source of truth.

// Vite resolves the asset import to its final URL (with hash on build); the
// card shows it keeping the image's original aspect ratio.
//
// TEMPORARY PLACEHOLDER: for now every entry uses this same image only to
// preview the layout. Replace each entry's `image` with its own asset when
// available.
import githubImage from '../assets/images/github.png'

export interface McpEntry {
  id: string
  name: string
  description: string
  // Accent color of the entry; it tints the avatar generated by `mcpIcon`.
  accent: string
  // Own image (optional). If missing, an avatar is generated with `mcpIcon`.
  image?: string
}

export const mcpCatalog: McpEntry[] = [
  {
    id: 'github',
    name: 'GitHub',
    description: 'Lee y gestiona repositorios, issues y pull requests sin salir del chat.',
    accent: '#1c1c1a',
    image: githubImage,
  },
  {
    id: 'filesystem',
    name: 'Filesystem',
    description: 'Explora y edita archivos locales con permisos acotados a una carpeta.',
    accent: '#f97316',
    image: githubImage,
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'Consulta bases de datos en lenguaje natural y revisa esquemas al vuelo.',
    accent: '#2f6f9f',
    image: githubImage,
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Busca conversaciones, resume canales y envia mensajes a tu equipo.',
    accent: '#5b3d5b',
    image: githubImage,
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer',
    description: 'Automatiza el navegador para abrir paginas, capturar pantallas y extraer datos.',
    accent: '#3a7d44',
    image: githubImage,
  },
]

// Generates the avatar of each MCP as an SVG data URI: a gradient with the
// name's initial. Keeps the view self-contained (no remote image dependencies)
// and gives a marketplace feel consistent with the visual identity.
export function mcpIcon(entry: McpEntry): string {
  const letter = entry.name.charAt(0).toUpperCase()
  const svg = [
    `<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 96 96">`,
    `<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">`,
    `<stop offset="0" stop-color="${entry.accent}"/>`,
    `<stop offset="1" stop-color="#fef9ed"/>`,
    `</linearGradient></defs>`,
    `<rect width="96" height="96" rx="22" fill="url(#g)"/>`,
    `<text x="50%" y="54%" dominant-baseline="middle" text-anchor="middle" `,
    `font-family="Red Hat Mono, ui-monospace, monospace" font-size="44" `,
    `font-weight="700" fill="#fef9ed">${letter}</text>`,
    `</svg>`,
  ].join('')
  return `data:image/svg+xml,${encodeURIComponent(svg)}`
}
